suppressMessages(library(BSgenome.Hsapiens.UCSC.hg38))
suppressMessages(library(GenomicRanges))
suppressMessages(library(data.table))
suppressMessages(library(seqinr))
suppressMessages(library(stringr))
suppressMessages(library(magrittr))
